### ISSUE TITLE
Need `arena get` json and yaml output 

### ISSUE THREAD

**Issue by cheyang** [kubeflow/arena#149]
Json output:
```
arena get tf-git -ojson
{
    "name": "tf-git",
    "namespace": "default",
    "duration": "0s",
    "status": "FAILED",
    "trainer": "tfjob",
    "instances": [
        {
            "status": "Failed",
            "name": "tf-git-chief-0",
            "age": "0s",
            "node": "192.168.0.199"
        }
    ]
}
```

yaml output

```
arena get tf-git -oyaml
name: tf-git
namespace: default
duration: 0s
status: FAILED
trainer: tfjob
tensorboard: ""
instances:
- status: Failed
  name: tf-git-chief-0
  age: 0s
  node: 192.168.0.199
```
