### ISSUE TITLE
sparkjob能否人工指定service-account?

### ISSUE THREAD

**Issue by Alienfeel** [kubeflow/arena#612]
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: {{ .Release.Name }}
  labels:
    version: 2.4.5
    release: {{ .Release.Name }}
    app: {{ template "sparkjob.name" . }}
    createdBy: "SparkJob"
spec:
  type: {{ .Values.Lang }}
  mode: cluster
  image: {{ .Values.Image }}
  imagePullPolicy: Always
  mainClass: {{ .Values.MainClass }}
  mainApplicationFile: {{ .Values.Jar }}
  sparkVersion: "2.4.5"
  restartPolicy:
    type: Never
  driver:
    cores: {{ .Values.Driver.CPURequest }}
    memory: {{ .Values.Driver.MemoryRequest }}
    labels:
      **version: 2.4.5**
      release: {{ .Release.Name }}
      app: {{ template "sparkjob.name" . }}
      createdBy: "SparkJob"
    **serviceAccount: spark**
  executor:
    cores: {{ .Values.Executor.CPURequest }}
    instances: {{ .Values.Executor.Replicas }}
    memory: {{ .Values.Executor.MemoryRequest }}
    labels:
      version: 2.4.5
      release: {{ .Release.Name }}
      app: {{ template "sparkjob.name" . }}
      createdBy: "SparkJob"
```

1. serviceAccount能否人工指定？
2. sparkVersion 能否放到values.yaml中配置？
